# this configuration is copy from docker example.
# before docker-compose up, please follow this link
# https://docs.docker.com/registry/configuration/
# to change the configuration options for production.

registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/ca.crt
    REGISTRY_HTTP_TLS_KEY: /certs/ca.key
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  volumes:
    - /registry/data:/var/lib/registry
    - /registry/certs:/certs
  log:
    level: info
    formatter: json
    fields:
      service: registry
      environment: staging