db:
  image: postgres


webapp:
  build: .
  working_dir: /app
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/app
  ports:
    - "8000:8000"
  links:
    - db


nginx:
  image: nginx
  volumes:
    - nginx:/etc/nginx/
  ports:
    - "80:80"
  links:
    - webapp